### ISSUE TITLE
README

### ISSUE THREAD

**Issue by karthikmurugappan** [karthikmurugappan/prework-study-guide#4]
# README

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN the prework project repository,
WHEN I view the README for the repository,
THEN I can see a professional README that provides information on the project and how to use it

**Comment by AmitGitHb** [comment]
Hey Karthik, can you elaborate the issue here? explain what is prework project?

**Comment by AmitGitHb** [comment]
Great and Goodluck.
